; -----------------------------------------------------------
; CBM kernal equates (C_ prevents naming collisions)
; -----------------------------------------------------------
C_STATUS	:=	$90
C_SECOND	:=	$ff93
C_TKSA	:=	$ff96
C_ACPTR	:=	$ffa5
C_CIOUT	:=	$ffa8
C_UNTLK	:=	$ffab
C_UNLSN	:=	$ffae
C_LISTEN	:=	$ffb1
C_TALK	:=	$ffb4
C_CHKIN	:=	$ffc6
C_CHKOUT	:=	$ffc9
C_CHRIN	:=	$ffcf
C_CHROUT	:=	$ffd2
C_CLOSE	:=	$ffc3
C_CLRCHN	:=	$ffcc
C_OPEN	:=	$ffc0
C_SETLFS	:=	$ffba
C_SETNAM	:=	$ffbd
C_SETBNK	:=	$ff68

