; -----------------------------------------------------------
; uIecSwitch.inc (include file for uIecSwitch)
; -----------------------------------------------------------
MAIN_T	=	40
MAIN_B	=	158
MAIN_L	=	56
MAIN_R	=	256
LIST_T	=	48
LIST_B	=	150
LIST_L	=	64
LIST_R	=	192
SCROLL_B	=	184
MAX_LIST	=	10
THUMB_HI	=	16
THUMB_WD	=	5
THUMBTOP	=	LIST_T+8
THUMB_L	=	SCROLL_B+2
THUMBMIN	=	8
THUMBMAX	=	(LIST_B-8)-(LIST_T+8)
;CLICK_COUNT	=	30	;should be in geosSym, but isn't
